astra_db:
  collection_name: "ecommerce_data"

embedding_model:
  model_name: "text-embedding-3-small"
  provider: "openai"

retriever:
  top_k: 3
  search_type: "similarity"

llm:
  groq:
    model_name: "deepseek-r1-distill-llama-70b"
    provider: "groq"
    temperature: 0
    max_output_tokens: 2048

  openai:
    model_name: "gpt-4o-mini"
    provider: "openai"
    temperature: 0
    max_output_tokens: 1000

chunking:
  chunk_size: 1000
  chunk_overlap: 300